sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
      dist: xenial
install:
  pip install pytest pytest-asyncio sanic aiohttp
script: 
  sh test.sh
  #chmod u+x test.sh && sh test.sh